### ISSUE TITLE
Link display permissions

### ISSUE THREAD

**Issue by mmcev106** [lsgs/redcap-tableau-wdc#1]
We're considering requiring design rights for all project links by default.  If we made that change, would you want to override it for this module so any user could see the instructions link?

**Comment by lsgs** [comment]
Yes, this would be an example of a module where I'd want the link displayed to users that do not have design rights. The Tableau Connector would be most applicable to users with data export rights.

Probably ideal would be if we could specify for a user/role whether a module's link/s is/are displayed - similar to how we can currently control access to the project module configuration:
![image](https://user-images.githubusercontent.com/7444426/38394890-998bf9cc-3973-11e8-8041-9ec3927271c6.png)

Because a module may have multiple links, and different permissions may be desired for different links, perhaps this would be best specified in the config.json somehow, or in the Control Centre config, rather than on projects' User Rights pages?

**Comment by mmcev106** [comment]
All of the above sounds great to me.  The current plan is simply to change the default behavior of the redcap_module_link_check_display() hook to require design rights.  I'm afraid more than that might be outside the scope of what I can realistically work on at the moment.

**Comment by mmcev106** [comment]
The following pull request should take care of this:

https://github.com/lsgs/redcap-tableau-wdc/pull/2
