### ISSUE TITLE
RedCap Live connection

### ISSUE THREAD

**Issue by ChantKatrjian** [lsgs/redcap-tableau-wdc#20]
Are live connections not supported for RedCap-Tableau data transfers yet?

**Comment by lsgs** [comment]
It is Tableau that requests data from REDCap rather than REDCap pushing to Tableau, so that would be something on the Tableau side, I reckon, @ChantKatrjian. On the REDCap side it is just hooking in to the regular API which can provide a response whenever it is requested. 

Note this external module is not being actively supported anymore since the functionality was incorporated into REDCap's core in 2021.
